[package]
name = "flex_macros"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
chrono = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
semver = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }
